# Generated by Django 5.2.7 on 2025-10-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=100, verbose_name="Место")),
                ("time", models.TimeField(verbose_name="Время")),
                ("action", models.CharField(max_length=150, verbose_name="Действие")),
                (
                    "pleasant_habit",
                    models.BooleanField(
                        default=False, verbose_name="Приятная привычка"
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Периодичность (в днях)"
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Вознаграждение"
                    ),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        default=120, verbose_name="Время на выполнение (в секундах)"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Публичная"),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
