# Generated by Django 5.2.7 on 2025-10-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="status",
            field=models.CharField(
                choices=[
                    ("started", "запущена"),
                    ("completed", "выполнена"),
                    ("failed", "провалена"),
                ],
                default="started",
                max_length=15,
            ),
        ),
    ]
