# Generated by Django 5.2.7 on 2025-10-15 05:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_habit_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="habit",
            name="last_completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последнее выполнение"
            ),
        ),
    ]
